### ISSUE TITLE
Yargs async

### ISSUE THREAD

**Issue by mleguen** [yargs/yargsa#4]
Follow-up of yargs/yargs#1420.

If we are going to introduce a breaking change by changing .parse() return type (and the like), I think that, now that we are planning to drop node 6 support, we should go further by making .parse() async, ie _always_ returning a promise.

This would not be a pain for our users, as they could use async/await too in their now at-least-node-8-compatible code. I am going to post some future API use examples here to illustrate this.

This would also ease the work a lot for us, and simplify already existing code (we would no longer have to deal with "maybe promises"). I am also going to post the intended approach here.

**Comment by bcoe** [comment]
@mleguen I went ahead and moved this over to yargsa, let's take our liberties in this repo:

1. experimenting with `async`/`await`, `modules`, etc.
2. not being afraid to break the existing API.

**Comment by bcoe** [comment]
CC: @petrgrishin, @Goodluckhf 👋 can we combine efforts here, and try to flesh out what a an ideal async version of yargs would look like.

If we can figure out how to add this to yargs in an additive way, what I'm picturing is we can perhaps point folks with an async use-case towards this module, without breaking the API of the synchronous version of yargs.

**Comment by mleguen** [comment]
> @mleguen do you think you'd be open to making an attempt at PR on yargsa? If we want to start simple, it could literally be a fork of yargs, but with your async work from this branch ...

Sure, this is the 1st item on my todo.

**Comment by mleguen** [comment]
New approach in yargs/yargs#1487
